### ISSUE TITLE
A better way to do ROUND money methods

### ISSUE THREAD

**Issue by vieiraroger** [vieiraroger/pcr-money#1]
Today the methods are passed as a string:

- 'round'
- 'truncation'
- 'floor'
- 'ceil'

But in my opnian this isnt the best way to do, because a developer that will be use this method need to know the strings.
You can see the static funcion here:
Line 12: https://github.com/vieiraroger/pcr-money/blob/main/src/pcr_money/money.py

Some ideias how to improve that? Enums?

**Comment by Lukempol** [comment]
I would like to help improve the handle_value function

**Comment by vieiraroger** [comment]
Fell free to open PR with yout improvement
